### Register User
@baseUrl = http://localhost:9595
@authToken = {{auth_login.response.body.token}}
@categoryGroupId = {{category_group_create.response.body.id}}
@categoryId = {{category_create.response.body.id}}

### Register User
# @name auth_register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "Arthur",
  "password": "a"
}

### Login User
# @name auth_login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "Arthur",
  "password": "a"
}

### Admin test
# @name admin_test_token
GET {{baseUrl}}/admin/test-token
Authorization: Bearer {{authToken}}

### Create Category Group
# @name category_group_create
POST {{baseUrl}}/category-group/create
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "My Category Group"
}

### Get Category Group
# @name category_group_get
GET {{baseUrl}}/category-group/{{categoryGroupId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Delete Category Group
# @name category_group_delete
DELETE {{baseUrl}}/category-group/{{categoryGroupId}}
Authorization: Bearer {{authToken}}

### Create Category
# @name category_create
POST {{baseUrl}}/category/create
Authorization: Bearer {{authToken}}

{
  "name": "My Category",
  "group_id": "{{categoryGroupId}}"
}

### Get Category
# @name category_get
GET {{baseUrl}}/category/{{categoryId}}
Authorization: Bearer {{authToken}}

### Delete Category
# @name category_delete
DELETE {{baseUrl}}/category/{{categoryId}}
Authorization: Bearer {{authToken}}
